### ISSUE TITLE
xdaportal.disqus.com

### ISSUE THREAD

**Issue by p1r473** [soteria-nou/domain-list#10]
Not a malicious domain. Used for discussing Android apps.

**Comment by jaka** [comment]
I put every domain in a category where it in my opinion should be. Subdomains of disqus.com are widgets (add-ons) for websites that would like to obtain some feedback. As in most cases, Referer from request header contains the address of the previous web page so disqus.com is able to gain some information as third-party from visitors.

Excluded in 4d8f5c01791b2786f9142138fdfacef3cc6db2ad

**Comment by p1r473** [comment]
Thanks!
