### ISSUE TITLE
fd-geoycpi-uno-deluxe.gycpi.b.yahoodns.net

### ISSUE THREAD

**Issue by p1r473** [soteria-nou/domain-list#11]
This is a Yahoo DNS server and is not malicious

**Comment by jaka** [comment]
Could be, but it also give a location for a given IP address.

However, excluded in 4d8f5c01791b2786f9142138fdfacef3cc6db2

**Comment by p1r473** [comment]
Thanks!

**Comment by p1r473** [comment]
@jaka Even though excluded, seems to still be on the list!

**Comment by jaka** [comment]
Yes, it's listed in `excluded.txt` file. This file's only purpose is keeping whitelisted domains in one place and should not be used is DNS related software.

**Comment by p1r473** [comment]
@jaka its in analytics.txt

**Comment by jaka** [comment]
In master branch, but not in cleaned branch.

**Comment by p1r473** [comment]
What is the difference of the branches, and what URLs should I be using for my PiHole then?
Currently using 
```https://raw.githubusercontent.com/soteria-nou/domain-list/master/ads.txt
https://raw.githubusercontent.com/soteria-nou/domain-list/master/affiliate.txt
https://raw.githubusercontent.com/soteria-nou/domain-list/master/analytics.txt
https://raw.githubusercontent.com/soteria-nou/domain-list/master/enrichments.txt
https://raw.githubusercontent.com/soteria-nou/domain-list/master/fake.txt
https://raw.githubusercontent.com/soteria-nou/domain-list/master/widgets.txt
```

**Comment by jaka** [comment]
Instead of `master` use `cleaned`, e.g.
```
https://raw.githubusercontent.com/soteria-nou/domain-list/cleaned/analytics.txt
```

**Comment by p1r473** [comment]
So Master branch includes everything, and cleaned removed user reported false positives?
