### ISSUE TITLE
*.cloudfront.net

### ISSUE THREAD

**Issue by p1r473** [soteria-nou/domain-list#9]
Amazon CloudFront is a fast content delivery network (CDN) service that securely delivers data, videos, applications, and APIs to customers globally
Not all Cloudfront is Ads

We should not be blocking it everywhere.

Here is an icon image on a website I was browsing that failed to load due to us blocking Cloudfront:
https://d3e1078hs60k37.cloudfront.net/site_files/images/icons/mv-all-icon.svg

Ex of a broken site:

![image](https://user-images.githubusercontent.com/9235633/79360865-83776400-7f12-11ea-86d3-3fbaa1a0db96.png)
![image](https://user-images.githubusercontent.com/9235633/79360884-8a05db80-7f12-11ea-9622-62290f780e48.png)

**Comment by p1r473** [comment]
the 2 domains I saw that were not ads but were actual sites were
d1f8f9xcsvx3ha.cloudfront.net
d3e1078hs60k37.cloudfront.net
If we want to whitelist just these

**Comment by jaka** [comment]
Ad networks are abusing Cloudflare to hide themselves.

Excluded in 4d8f5c01791b2786f9142138fdfacef3cc6db2ad

**Comment by p1r473** [comment]
Thanks!
